---
abstract: "Static data script support package for SSDT post-deployment steps, Ded MedVed..\r"
author:
  - 'Ded MedVed <dedmedved@cpan>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: VSGDR-StaticData
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  DBD::ODBC: 0
  DBI: 0
  Data::Dumper: 0
  Getopt::Euclid: 0
  Graph: 0.9
  List::Util: 1
  Modern::Perl: 0
  POSIX: 0
  Test::More: 0
  autodie: 0
  indirect: 0
  perl: 0
  version: 0
version: 0.09
